var a = 1;
var b = 2;
var c = 3;
var d = 4;
var e = 5;
var f = 6;
var g = 7;
var h = 8;
var i = 9;
var j = 10;

console.log(a + c);
console.log(b + e);
console.log(j - c);
console.log(a - i);
console.log(g * b);
console.log(i * d);
console.log(g / j);
console.log(h / e);
console.log(g ++);
console.log(d ++);
console.log(i --);
console.log(b--);